// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKAOuyUzuqk5Yc56uf0lCXcAQDA_ISkyo',
    appId: '1:439799132801:web:e262b7eaf01d0d18dcd380',
    messagingSenderId: '439799132801',
    projectId: 'authtutorial-2b050',
    authDomain: 'authtutorial-2b050.firebaseapp.com',
    storageBucket: 'authtutorial-2b050.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCf0oGyDj1jdsvhe2i4OmPKWsY9sKqJ_E',
    appId: '1:439799132801:android:208a28a7cf7903acdcd380',
    messagingSenderId: '439799132801',
    projectId: 'authtutorial-2b050',
    storageBucket: 'authtutorial-2b050.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmi0w_FIoBvwn9Ma_sfmhE5LV-xIp-ewQ',
    appId: '1:439799132801:ios:090acbdd5d162a5adcd380',
    messagingSenderId: '439799132801',
    projectId: 'authtutorial-2b050',
    storageBucket: 'authtutorial-2b050.appspot.com',
    iosClientId: '439799132801-797hbamhlmb40vfjks7pce9u83qpg3sa.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAuthTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmi0w_FIoBvwn9Ma_sfmhE5LV-xIp-ewQ',
    appId: '1:439799132801:ios:090acbdd5d162a5adcd380',
    messagingSenderId: '439799132801',
    projectId: 'authtutorial-2b050',
    storageBucket: 'authtutorial-2b050.appspot.com',
    iosClientId: '439799132801-797hbamhlmb40vfjks7pce9u83qpg3sa.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAuthTutorial',
  );
}
